name: testapp
description: Онлайн тестілеу және білім деңгейін бағалауға арналған қосымша
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.0.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  flutterfire_cli: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#F5F7FA" # Өзіңіздің AppTheme.background түсіңізді қойсаңыз болады
  adaptive_icon_foreground: "assets/icons/app_icon.png"
